// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.1_@types+node@22.10.5_eslint@9.17.0_rollup@3.29.5_typescript@5.6.3_vite@6.0.7_vue-tsc@2.2.0/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/contentrain/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/runtime/server/api/query').default>>>>
    }
    '/api/contentrain/load': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/runtime/server/api/load').default>>>>
    }
  }
}
export {}