// Generated by @contentrain/sdk
// Do not edit this file manually

import type { BaseModel } from '@contentrain/sdk'

export interface IBlogPosts extends BaseModel {
  title: string
  content: string
  slug: string
  categoryId?: string
  'categoryId-data'?: ICategories
}

export interface IPostAuthors extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  fullname: string
  'avatar-image'?: string
  role?: string
}

export interface IBlogCategories extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  name: string
  description?: string
  'sub-categories'?: string[]
  'sub-categories-data'?: IBlogCategories[]
  tip?: string
}

export interface IBitkiBilgiBankasi extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title: string
  description?: string
  slug: string
  content: any
  image: string
  author?: string
  'author-data'?: IPostAuthors
}

export interface IFaq extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title: string
  content: any
  description: string
}

export interface ISEOLinks extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  text: string
  link: string
}

export interface IBannerItems extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  order: number
  image?: string
  'image-source'?: string
  link: string
  'image-alt'?: string
  items?: string[]
  'items-data'?: IBannerItems[]
  'promotion-id'?: string
  'promotion-name'?: string
  'creative-name'?: string
  'creative-slot'?: string
  'location-id'?: string
}

export interface IMainBanner extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  order: number
  items?: string[]
  'items-data'?: IBannerItems[]
}

export interface ICampaigns extends BaseModel {
  slug: string
  content: string
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title: string
  description?: string
  image?: string
  'image-alt'?: string
  'image-source'?: string
  'campaign-card-text': string
  'button-text': string
}

export interface IPages extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  heading?: string
  image?: string
  'image-src'?: string
  'image-alt'?: string
  content?: any
  slug: string
  'meta-tags'?: string[]
  'meta-tags-data'?: IMetaTags[]
  'breadcrumb-banner-image'?: string
}

export interface ISozlesmelerVeKVKK extends BaseModel {
  slug: string
  content: string
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  type: string
  title: string
}

export interface IDestekKategoriler extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title: string
  'soru-cevap': string[]
  'soru-cevap-data'?: IDestekSorular[]
  order: number
}

export interface IDestekSorular extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  soru: string
  cevap: string
  title: string
  order?: number
}

export interface IUserPanelEmptyState extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  icon: string
  title: string
  buttontext: string
  'panel-id': string
  buttonlink?: string
}

export interface ISEO extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  pagename?: string
}

export interface IFormField extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  label?: string
  placeholder?: string
  options?: string
}

export interface IForm extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  'form-fields': string[]
  'form-fields-data'?: IFormField[]
  'form-source-url': string
  'form-title'?: string
  'form-subtitle'?: string
  'form-submit-text'?: string
}

export interface IMetaTags extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  name: string
  content: string
  description?: string
}

export interface IOrderNote extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  category: string
  messages: string
}

export interface IHeaderTopBar extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title?: string
  link?: string
  'image-src'?: string
  'image-alt'?: string
  image?: string
}

export interface IBenefitsBanner extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title?: string
  'image-source'?: string
  'image-alt'?: string
  image?: string
}

export interface INewsletterBanner extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title?: string
  description?: string
  image?: string
}

export interface IProductBanner extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  text?: string
  icon?: string
}

export interface IBrands extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  guid: string
  description?: string
  logo?: string
  title: string
}

export interface IShippingDetails extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  guid: string
  content: string
  'sub-category': string
  image?: string
}

export interface IFeaturedProducts extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title: string
  'image-alt'?: string
  'submit-text'?: string
  friendlyurl: string
  image: string
  'kategori-friendly-url'?: string
}

export interface IConnectionBar extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  'featured-products'?: string[]
  'featured-products-data'?: IFeaturedProducts[]
  greeting?: string
}

export interface IMenuCategory extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title: string
  'friendly-url': string
  guid: string
}

export interface IFooterMenus extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title?: string
  justify?: string
  flex?: string
  items?: string[]
  'items-data'?: IFooterItem[]
  order?: number
}

export interface IFooterItem extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  order: number
  type?: string
  text?: string
  src?: string
  link?: string
  alt?: string
  icon?: string
  items?: string[]
  'items-data'?: IFooterItem[]
  flex?: string
  image?: string
  justify?: string
}

export interface ILogo extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  image?: string
  'image-src'?: string
  'image-alt'?: string
  order: number
}

export interface ISocialMedia extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  content: string[]
  'content-data'?: IFooterItem[]
}

export interface IFooterBottomItems extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  text?: string
  flex?: string
  justify?: string
  items?: string[]
  'items-data'?: IFooterItem[]
  order: number
}

export interface ILocationModal extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  text: string
  placeholder?: string
  image?: string
  'image-src'?: string
  'image-alt'?: string
  'footer-text'?: string
}

export interface IPaymentOptionsBanner extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title?: string
  logos: string[]
  'logos-data'?: ILogo[]
}

export interface IHeaderLogo extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  type: string
  'image-alt'?: string
  'image-src'?: string
  image?: string
}

export interface IContactInfo extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title?: string
  justify?: string
  flex?: string
  items?: string[]
  'items-data'?: IFooterItem[]
  order?: number
}

export interface IShowcaseViewStyle extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  'slider-view'?: boolean
}

export interface ICorporateSections extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title: string
  description: string
  buttontext?: string
  buttonlink?: string
  name: string
  image?: string
  'image-source'?: string
  'image-alt'?: string
  items?: string[]
  'items-data'?: ICorporateSectionItems[]
}

export interface ICorporateSectionItems extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  text?: string
  name?: string
  image?: string
  'image-alt'?: string
  icon?: string[]
  'icon-data'?: ICorporateItemIcons[]
  link?: string
  order: number
}

export interface ICorporateItemIcons extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  'icon-theme-name': string
  'icon-name': string
  'icon-color'?: any
  'icon-background-color'?: any
}

export interface ICorporateBannerCards extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title: string
  description: string
  icon?: string
  'icon-data'?: ICorporateItemIcons
}

export interface ICorporateFaq extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  question: string
  answer: string
  order: number
}

export interface IStickyButtonThemes extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  'background-color'?: any
  'active-background-color'?: any
  'text-color'?: any
  'active-text-color'?: any
  'border-color'?: any
  'active-border-color'?: any
  'icon-color'?: any
  'active-icon-color'?: any
  name?: string
}

export interface ISpecialDays extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  date?: string
  name?: string
  theme?: string
  'theme-data'?: IStickyButtonThemes
  icon?: string
  'active-icon'?: string
}

export interface ICustomMenu extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  title?: string
  'title-bold'?: boolean
  'title-italic'?: boolean
  'title-icon'?: string
  items?: string[]
  'items-data'?: ICustomMenuItems[]
  'see-all-url'?: string
  image?: string
  'image-alt'?: string
  link?: string
  order?: number
}

export interface ICustomMenuItems extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  text?: string
  image?: string
  'image-alt'?: string
  link?: string
}

export interface IFormFields extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  name: string
  type: string
  'type-data'?: IFieldTypes
  label?: string
  'label-data'?: ILabels
  placeholder?: string
  'placeholder-data'?: IPlaceholders
  options?: string[]
  'options-data'?: IOptions[]
  autocomplete?: string
  'autocomplete-data'?: IAutocompleteTypes
}

export interface IFieldTypes extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  text: string
  value: string
}

export interface ILabels extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  text: string
}

export interface IPlaceholders extends BaseModel {
  text: string
}

export interface IOptions extends BaseModel {
  text: string
  value: string
  group: string
}

export interface IAutocompleteTypes extends BaseModel {
  createdAt: string
  updatedAt: string
  ID: string
  status: 'draft' | 'changed' | 'publish'
  name: string
  value: string
}

export interface ContentrainTypeMap {
  'blog-posts': IBlogPosts
  'post-authors': IPostAuthors
  'blog-categories': IBlogCategories
  'bitki-bilgi-bankasi': IBitkiBilgiBankasi
  'faq': IFaq
  'seo-links': ISEOLinks
  'banner-items': IBannerItems
  'banner-items-1': IMainBanner
  'campaigns': ICampaigns
  'pages': IPages
  'sozlesmeler-ve-kvkk': ISozlesmelerVeKVKK
  'destek-sorular': IDestekKategoriler
  'destek-soru': IDestekSorular
  'userpanelemptystate': IUserPanelEmptyState
  'seo': ISEO
  'form-field': IFormField
  'form': IForm
  'meta-tags': IMetaTags
  'order-note': IOrderNote
  'header-top-bar': IHeaderTopBar
  'benefits-banner': IBenefitsBanner
  'newsletter-banner': INewsletterBanner
  'product-banner': IProductBanner
  'brands': IBrands
  'shipping-details': IShippingDetails
  'featured-product': IFeaturedProducts
  'connection-bar': IConnectionBar
  'menu-category': IMenuCategory
  'footer-menus': IFooterMenus
  'footer-item': IFooterItem
  'logo': ILogo
  'social-media': ISocialMedia
  'footer-bottom-items': IFooterBottomItems
  'location-modal': ILocationModal
  'payment-options-banner': IPaymentOptionsBanner
  'header-logo': IHeaderLogo
  'footer-menus-1': IContactInfo
  'showcase-view-style': IShowcaseViewStyle
  'corporate-sections': ICorporateSections
  'corporate-section-items': ICorporateSectionItems
  'corporate-item-icons': ICorporateItemIcons
  'corporate-banner-cards': ICorporateBannerCards
  'corporate-faqs': ICorporateFaq
  'sticky-button-themes': IStickyButtonThemes
  'special-days': ISpecialDays
  'custom-menu': ICustomMenu
  'custom-menu-items': ICustomMenuItems
  'form-field-1': IFormFields
  'field-types': IFieldTypes
  'labels': ILabels
  'placeholders': IPlaceholders
  'options': IOptions
  'autocomplete-types': IAutocompleteTypes
}


// Relations
export type ModelRelations = {
  'blog-posts': {
    categoryId: {
      model: 'categories',
      type: 'one-to-one'
    }
  },
  'post-authors': {
    [key: string]: { model: string, type: string }
  },
  'blog-categories': {
    'sub-categories': {
      model: 'blog-categories',
      type: 'one-to-many'
    }
  },
  'bitki-bilgi-bankasi': {
    author: {
      model: 'post-authors',
      type: 'one-to-one'
    }
  },
  'faq': {
    [key: string]: { model: string, type: string }
  },
  'seo-links': {
    [key: string]: { model: string, type: string }
  },
  'banner-items': {
    items: {
      model: 'banner-items',
      type: 'one-to-many'
    }
  },
  'banner-items-1': {
    items: {
      model: 'banner-items',
      type: 'one-to-many'
    }
  },
  'campaigns': {
    [key: string]: { model: string, type: string }
  },
  'pages': {
    'meta-tags': {
      model: 'meta-tags',
      type: 'one-to-many'
    }
  },
  'sozlesmeler-ve-kvkk': {
    [key: string]: { model: string, type: string }
  },
  'destek-sorular': {
    'soru-cevap': {
      model: 'destek-soru',
      type: 'one-to-many'
    }
  },
  'destek-soru': {
    [key: string]: { model: string, type: string }
  },
  'userpanelemptystate': {
    [key: string]: { model: string, type: string }
  },
  'seo': {
    [key: string]: { model: string, type: string }
  },
  'form-field': {
    [key: string]: { model: string, type: string }
  },
  'form': {
    'form-fields': {
      model: 'form-field',
      type: 'one-to-many'
    }
  },
  'meta-tags': {
    [key: string]: { model: string, type: string }
  },
  'order-note': {
    [key: string]: { model: string, type: string }
  },
  'header-top-bar': {
    [key: string]: { model: string, type: string }
  },
  'benefits-banner': {
    [key: string]: { model: string, type: string }
  },
  'newsletter-banner': {
    [key: string]: { model: string, type: string }
  },
  'product-banner': {
    [key: string]: { model: string, type: string }
  },
  'brands': {
    [key: string]: { model: string, type: string }
  },
  'shipping-details': {
    [key: string]: { model: string, type: string }
  },
  'featured-product': {
    [key: string]: { model: string, type: string }
  },
  'connection-bar': {
    'featured-products': {
      model: 'featured-product',
      type: 'one-to-many'
    }
  },
  'menu-category': {
    [key: string]: { model: string, type: string }
  },
  'footer-menus': {
    items: {
      model: 'footer-item',
      type: 'one-to-many'
    }
  },
  'footer-item': {
    items: {
      model: 'footer-item',
      type: 'one-to-many'
    }
  },
  'logo': {
    [key: string]: { model: string, type: string }
  },
  'social-media': {
    content: {
      model: 'footer-item',
      type: 'one-to-many'
    }
  },
  'footer-bottom-items': {
    items: {
      model: 'footer-item',
      type: 'one-to-many'
    }
  },
  'location-modal': {
    [key: string]: { model: string, type: string }
  },
  'payment-options-banner': {
    logos: {
      model: 'logo',
      type: 'one-to-many'
    }
  },
  'header-logo': {
    [key: string]: { model: string, type: string }
  },
  'footer-menus-1': {
    items: {
      model: 'footer-item',
      type: 'one-to-many'
    }
  },
  'showcase-view-style': {
    [key: string]: { model: string, type: string }
  },
  'corporate-sections': {
    items: {
      model: 'corporate-section-items',
      type: 'one-to-many'
    }
  },
  'corporate-section-items': {
    icon: {
      model: 'corporate-item-icons',
      type: 'one-to-many'
    }
  },
  'corporate-item-icons': {
    [key: string]: { model: string, type: string }
  },
  'corporate-banner-cards': {
    icon: {
      model: 'corporate-item-icons',
      type: 'one-to-one'
    }
  },
  'corporate-faqs': {
    [key: string]: { model: string, type: string }
  },
  'sticky-button-themes': {
    [key: string]: { model: string, type: string }
  },
  'special-days': {
    theme: {
      model: 'sticky-button-themes',
      type: 'one-to-one'
    }
  },
  'custom-menu': {
    items: {
      model: 'custom-menu-items',
      type: 'one-to-many'
    }
  },
  'custom-menu-items': {
    [key: string]: { model: string, type: string }
  },
  'form-field-1': {
    type: {
      model: 'field-types',
      type: 'one-to-one'
    },
    label: {
      model: 'labels',
      type: 'one-to-one'
    },
    placeholder: {
      model: 'placeholders',
      type: 'one-to-one'
    },
    options: {
      model: 'options',
      type: 'one-to-many'
    },
    autocomplete: {
      model: 'autocomplete-types',
      type: 'one-to-one'
    }
  },
  'field-types': {
    [key: string]: { model: string, type: string }
  },
  'labels': {
    [key: string]: { model: string, type: string }
  },
  'placeholders': {
    [key: string]: { model: string, type: string }
  },
  'options': {
    [key: string]: { model: string, type: string }
  },
  'autocomplete-types': {
    [key: string]: { model: string, type: string }
  }
}
