// Generated by scripts/generate-types.js
// Do not edit this file manually

export type Status = 'draft' | 'changed' | 'publish'

export interface BaseContentrainType {
  ID: string
  createdAt: string
  updatedAt: string
  status: Status
}

export type ModelId = 'autocomplete-types' | 'banner-items-1' | 'banner-items' | 'benefits-banner' | 'bitki-bilgi-bankasi' | 'blog-categories' | 'blog-posts' | 'brands' | 'campaigns' | 'connection-bar' | 'corporate-banner-cards' | 'corporate-faqs' | 'corporate-item-icons' | 'corporate-section-items' | 'corporate-sections' | 'custom-menu-items' | 'custom-menu' | 'destek-soru' | 'destek-sorular' | 'faq' | 'featured-product' | 'field-types' | 'footer-bottom-items' | 'footer-item' | 'footer-menus-1' | 'footer-menus' | 'form-field-1' | 'form-field' | 'form' | 'header-logo' | 'header-top-bar' | 'labels' | 'location-modal' | 'logo' | 'menu-category' | 'meta-tags' | 'newsletter-banner' | 'options' | 'order-note' | 'pages' | 'payment-options-banner' | 'placeholders' | 'post-authors' | 'product-banner' | 'seo-links' | 'seo' | 'shipping-details' | 'showcase-view-style' | 'social-media' | 'sozlesmeler-ve-kvkk' | 'special-days' | 'sticky-button-themes' | 'userpanelemptystate'

export interface IAutocompleteTypes extends BaseContentrainType {
  name: string
  value: string
}

export interface IMainBanner extends BaseContentrainType {
  'order': number
  'items'?: string[]
  'items-data'?: IBannerItems[]
}

export interface IBannerItems extends BaseContentrainType {
  'order': number
  'image'?: string
  'image-source'?: string
  'link': string
  'image-alt'?: string
  'promotion-id'?: string
  'promotion-name'?: string
  'creative-name'?: string
  'creative-slot'?: string
  'location-id'?: string
  'items'?: string[]
  'items-data'?: IBannerItems[]
}

export interface IBenefitsBanner extends BaseContentrainType {
  'title'?: string
  'image-source'?: string
  'image-alt'?: string
  'image'?: string
}

export interface IBitkiBilgiBankasi extends BaseContentrainType {
  'title': string
  'description'?: string
  'slug': string
  'content': string
  'image': string
  'author'?: string
  'author-data'?: IPostAuthors
}

export interface IBlogCategories extends BaseContentrainType {
  'name': string
  'description'?: string
  'tip'?: string
  'sub-categories'?: string[]
  'sub-categories-data'?: IBlogCategories[]
}

export interface IBlogPosts extends BaseContentrainType {
  'slug': string
  'content': string
  'title': string
  'cover-image'?: string
  'description': string
  'author': string
  'author-data'?: IPostAuthors
  'category'?: string
  'category-data'?: IBlogCategories
}

export interface IBrands extends BaseContentrainType {
  guid: string
  description?: string
  logo?: string
  title: string
}

export interface ICampaigns extends BaseContentrainType {
  'slug': string
  'content': string
  'title': string
  'description'?: string
  'image'?: string
  'image-alt'?: string
  'image-source'?: string
  'campaign-card-text': string
  'button-text': string
}

export interface IConnectionBar extends BaseContentrainType {
  'greeting'?: string
  'featured-products'?: string[]
  'featured-products-data'?: IFeaturedProducts[]
}

export interface ICorporateBannerCards extends BaseContentrainType {
  'title': string
  'description': string
  'icon'?: string
  'icon-data'?: ICorporateItemIcons
}

export interface ICorporateFaq extends BaseContentrainType {
  question: string
  answer: string
  order: number
}

export interface ICorporateItemIcons extends BaseContentrainType {
  'icon-theme-name': string
  'icon-name': string
  'icon-color'?: string
  'icon-background-color'?: string
}

export interface ICorporateSectionItems extends BaseContentrainType {
  'text'?: string
  'name'?: string
  'image'?: string
  'image-alt'?: string
  'link'?: string
  'order': number
  'icon'?: string[]
  'icon-data'?: ICorporateItemIcons[]
}

export interface ICorporateSections extends BaseContentrainType {
  'title': string
  'description': string
  'buttontext'?: string
  'buttonlink'?: string
  'name': string
  'image'?: string
  'image-source'?: string
  'image-alt'?: string
  'items'?: string[]
  'items-data'?: ICorporateSectionItems[]
}

export interface ICustomMenuItems extends BaseContentrainType {
  'text'?: string
  'image'?: string
  'image-alt'?: string
  'link'?: string
}

export interface ICustomMenu extends BaseContentrainType {
  'title'?: string
  'title-bold'?: boolean
  'title-italic'?: boolean
  'title-icon'?: string
  'see-all-url'?: string
  'image'?: string
  'image-alt'?: string
  'link'?: string
  'order'?: number
  'items'?: string[]
  'items-data'?: ICustomMenuItems[]
}

export interface IDestekSorular extends BaseContentrainType {
  soru: string
  cevap: string
  title: string
  order?: number
}

export interface IDestekKategoriler extends BaseContentrainType {
  'title': string
  'order': number
  'soru-cevap': string[]
  'soru-cevap-data'?: IDestekSorular[]
}

export interface IFaq extends BaseContentrainType {
  title: string
  content: string
  description: string
}

export interface IFeaturedProducts extends BaseContentrainType {
  'title': string
  'image-alt'?: string
  'submit-text'?: string
  'friendlyurl': string
  'image': string
  'kategori-friendly-url'?: string
}

export interface IFieldTypes extends BaseContentrainType {
  text: string
  value: string
}

export interface IFooterBottomItems extends BaseContentrainType {
  'text'?: string
  'flex'?: string
  'justify'?: string
  'order': number
  'items'?: string[]
  'items-data'?: IFooterItem[]
}

export interface IFooterItem extends BaseContentrainType {
  'order': number
  'type'?: string
  'text'?: string
  'src'?: string
  'link'?: string
  'alt'?: string
  'icon'?: string
  'flex'?: string
  'image'?: string
  'justify'?: string
  'items'?: string[]
  'items-data'?: IFooterItem[]
}

export interface IContactInfo extends BaseContentrainType {
  'title'?: string
  'justify'?: string
  'flex'?: string
  'order'?: number
  'items'?: string[]
  'items-data'?: IFooterItem[]
}

export interface IFooterMenus extends BaseContentrainType {
  'title'?: string
  'justify'?: string
  'flex'?: string
  'order'?: number
  'items'?: string[]
  'items-data'?: IFooterItem[]
}

export interface IFormFields extends BaseContentrainType {
  'name': string
  'type': string
  'type-data'?: IFieldTypes
  'label'?: string
  'label-data'?: ILabels
  'placeholder'?: string
  'placeholder-data'?: IPlaceholders
  'options'?: string[]
  'options-data'?: IOptions[]
  'autocomplete'?: string
  'autocomplete-data'?: IAutocompleteTypes
}

export interface IFormField extends BaseContentrainType {
  label?: string
  placeholder?: string
  options?: string[]
}

export interface IForm extends BaseContentrainType {
  'form-source-url': string
  'form-title'?: string
  'form-subtitle'?: string
  'form-submit-text'?: string
  'form-fields': string[]
  'form-fields-data'?: IFormField[]
}

export interface IHeaderLogo extends BaseContentrainType {
  'type': string
  'image-alt'?: string
  'image-src'?: string
  'image'?: string
}

export interface IHeaderTopBar extends BaseContentrainType {
  'title'?: string
  'link'?: string
  'image-src'?: string
  'image-alt'?: string
  'image'?: string
}

export interface ILabels extends BaseContentrainType {
  text: string
}

export interface ILocationModal extends BaseContentrainType {
  'text': string
  'placeholder'?: string
  'image'?: string
  'image-src'?: string
  'image-alt'?: string
  'footer-text'?: string
}

export interface ILogo extends BaseContentrainType {
  'image'?: string
  'image-src'?: string
  'image-alt'?: string
  'order': number
}

export interface IMenuCategory extends BaseContentrainType {
  'title': string
  'friendly-url': string
  'guid': string
}

export interface IMetaTags extends BaseContentrainType {
  name: string
  content: string
  description?: string
}

export interface INewsletterBanner extends BaseContentrainType {
  title?: string
  description?: string
  image?: string
}

export interface IOptions extends BaseContentrainType {
  text: string
  value: string
  group: string
}

export interface IOrderNote extends BaseContentrainType {
  category: string
  messages: string[]
}

export interface IPages extends BaseContentrainType {
  'heading'?: string
  'image'?: string
  'image-src'?: string
  'image-alt'?: string
  'content'?: string
  'slug': string
  'breadcrumb-banner-image'?: string
  'meta-tags'?: string[]
  'meta-tags-data'?: IMetaTags[]
}

export interface IPaymentOptionsBanner extends BaseContentrainType {
  'title'?: string
  'logos': string[]
  'logos-data'?: ILogo[]
}

export interface IPlaceholders extends BaseContentrainType {
  text: string
}

export interface IPostAuthors extends BaseContentrainType {
  'fullname': string
  'avatar-image'?: string
  'role'?: string
}

export interface IProductBanner extends BaseContentrainType {
  text?: string
  icon?: string
}

export interface ISEOLinks extends BaseContentrainType {
  text: string
  link: string
}

export interface ISEO extends BaseContentrainType {
  pagename?: string
}

export interface IShippingDetails extends BaseContentrainType {
  'guid': string
  'content': string
  'sub-category': string
  'image'?: string
}

export interface IShowcaseViewStyle extends BaseContentrainType {
  'slider-view'?: boolean
}

export interface ISocialMedia extends BaseContentrainType {
  'content': string[]
  'content-data'?: IFooterItem[]
}

export interface ISozlesmelerVeKVKK extends BaseContentrainType {
  slug: string
  content: string
  type: string
  title: string
}

export interface ISpecialDays extends BaseContentrainType {
  'date'?: string
  'name'?: string
  'icon'?: string
  'active-icon'?: string
  'theme'?: string
  'theme-data'?: IStickyButtonThemes
}

export interface IStickyButtonThemes extends BaseContentrainType {
  'background-color'?: string
  'active-background-color'?: string
  'text-color'?: string
  'active-text-color'?: string
  'border-color'?: string
  'active-border-color'?: string
  'icon-color'?: string
  'active-icon-color'?: string
  'name'?: string
}

export interface IUserPanelEmptyState extends BaseContentrainType {
  'icon': string
  'title': string
  'buttontext': string
  'panel-id': string
  'buttonlink'?: string
}

// Type mapping for model IDs to their respective interfaces
export type ContentrainTypeMap = {
  'autocomplete-types': IAutocompleteTypes
  'banner-items-1': IMainBanner
  'banner-items': IBannerItems
  'benefits-banner': IBenefitsBanner
  'bitki-bilgi-bankasi': IBitkiBilgiBankasi
  'blog-categories': IBlogCategories
  'blog-posts': IBlogPosts
  'brands': IBrands
  'campaigns': ICampaigns
  'connection-bar': IConnectionBar
  'corporate-banner-cards': ICorporateBannerCards
  'corporate-faqs': ICorporateFaq
  'corporate-item-icons': ICorporateItemIcons
  'corporate-section-items': ICorporateSectionItems
  'corporate-sections': ICorporateSections
  'custom-menu-items': ICustomMenuItems
  'custom-menu': ICustomMenu
  'destek-soru': IDestekSorular
  'destek-sorular': IDestekKategoriler
  'faq': IFaq
  'featured-product': IFeaturedProducts
  'field-types': IFieldTypes
  'footer-bottom-items': IFooterBottomItems
  'footer-item': IFooterItem
  'footer-menus-1': IContactInfo
  'footer-menus': IFooterMenus
  'form-field-1': IFormFields
  'form-field': IFormField
  'form': IForm
  'header-logo': IHeaderLogo
  'header-top-bar': IHeaderTopBar
  'labels': ILabels
  'location-modal': ILocationModal
  'logo': ILogo
  'menu-category': IMenuCategory
  'meta-tags': IMetaTags
  'newsletter-banner': INewsletterBanner
  'options': IOptions
  'order-note': IOrderNote
  'pages': IPages
  'payment-options-banner': IPaymentOptionsBanner
  'placeholders': IPlaceholders
  'post-authors': IPostAuthors
  'product-banner': IProductBanner
  'seo-links': ISEOLinks
  'seo': ISEO
  'shipping-details': IShippingDetails
  'showcase-view-style': IShowcaseViewStyle
  'social-media': ISocialMedia
  'sozlesmeler-ve-kvkk': ISozlesmelerVeKVKK
  'special-days': ISpecialDays
  'sticky-button-themes': IStickyButtonThemes
  'userpanelemptystate': IUserPanelEmptyState
}

// Relation Mappings
export type BannerItems1RelationFields = 'items'
export type BannerItemsRelationFields = 'items'
export type BitkiBilgiBankasiRelationFields = 'author'
export type BlogCategoriesRelationFields = 'sub-categories'
export type BlogPostsRelationFields = 'author' | 'category'
export type ConnectionBarRelationFields = 'featured-products'
export type CorporateBannerCardsRelationFields = 'icon'
export type CorporateSectionItemsRelationFields = 'icon'
export type CorporateSectionsRelationFields = 'items'
export type CustomMenuRelationFields = 'items'
export type DestekSorularRelationFields = 'soru-cevap'
export type FooterBottomItemsRelationFields = 'items'
export type FooterItemRelationFields = 'items'
export type FooterMenus1RelationFields = 'items'
export type FooterMenusRelationFields = 'items'
export type FormField1RelationFields = 'type' | 'label' | 'placeholder' | 'options' | 'autocomplete'
export type FormRelationFields = 'form-fields'
export type PagesRelationFields = 'meta-tags'
export type PaymentOptionsBannerRelationFields = 'logos'
export type SocialMediaRelationFields = 'content'
export type SpecialDaysRelationFields = 'theme'

export type ModelRelations = {
  'banner-items-1': {
    items: {
      model: 'banner-items'
      type: 'one-to-many'
    }
  }
  'banner-items': {
    items: {
      model: 'banner-items'
      type: 'one-to-many'
    }
  }
  'bitki-bilgi-bankasi': {
    author: {
      model: 'post-authors'
      type: 'one-to-one'
    }
  }
  'blog-categories': {
    'sub-categories': {
      model: 'blog-categories'
      type: 'one-to-many'
    }
  }
  'blog-posts': {
    author: {
      model: 'post-authors'
      type: 'one-to-one'
    }
    category: {
      model: 'blog-categories'
      type: 'one-to-one'
    }
  }
  'connection-bar': {
    'featured-products': {
      model: 'featured-product'
      type: 'one-to-many'
    }
  }
  'corporate-banner-cards': {
    icon: {
      model: 'corporate-item-icons'
      type: 'one-to-one'
    }
  }
  'corporate-section-items': {
    icon: {
      model: 'corporate-item-icons'
      type: 'one-to-many'
    }
  }
  'corporate-sections': {
    items: {
      model: 'corporate-section-items'
      type: 'one-to-many'
    }
  }
  'custom-menu': {
    items: {
      model: 'custom-menu-items'
      type: 'one-to-many'
    }
  }
  'destek-sorular': {
    'soru-cevap': {
      model: 'destek-soru'
      type: 'one-to-many'
    }
  }
  'footer-bottom-items': {
    items: {
      model: 'footer-item'
      type: 'one-to-many'
    }
  }
  'footer-item': {
    items: {
      model: 'footer-item'
      type: 'one-to-many'
    }
  }
  'footer-menus-1': {
    items: {
      model: 'footer-item'
      type: 'one-to-many'
    }
  }
  'footer-menus': {
    items: {
      model: 'footer-item'
      type: 'one-to-many'
    }
  }
  'form-field-1': {
    type: {
      model: 'field-types'
      type: 'one-to-one'
    }
    label: {
      model: 'labels'
      type: 'one-to-one'
    }
    placeholder: {
      model: 'placeholders'
      type: 'one-to-one'
    }
    options: {
      model: 'options'
      type: 'one-to-many'
    }
    autocomplete: {
      model: 'autocomplete-types'
      type: 'one-to-one'
    }
  }
  'form': {
    'form-fields': {
      model: 'form-field'
      type: 'one-to-many'
    }
  }
  'pages': {
    'meta-tags': {
      model: 'meta-tags'
      type: 'one-to-many'
    }
  }
  'payment-options-banner': {
    logos: {
      model: 'logo'
      type: 'one-to-many'
    }
  }
  'social-media': {
    content: {
      model: 'footer-item'
      type: 'one-to-many'
    }
  }
  'special-days': {
    theme: {
      model: 'sticky-button-themes'
      type: 'one-to-one'
    }
  }
}
